name: Jira Ticket Transition and Environment Info
on:
  workflow_dispatch:
    inputs:
      JIRA_ISSUE_KEY:
        description: 'Jira Ticket'
        required: true
        default: ''
jobs:
  jira-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Jira Ticket Helper
        uses: ./
        with:
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ vars.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_KEY: ${{ github.event.inputs.JIRA_ISSUE_KEY }}