name: Jira Issue Transition

on:
  pull_request:
    types: [opened]

jobs:
  slack-integration:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
      - uses: ./
        with:
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ vars.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          PR_TITLE_PATTERN: ${{ vars.PR_TITLE_PATTERN }}
          JIRA_ISSUE_TYPE_TRANSITION: ${{ vars.JIRA_ISSUE_TYPE_TRANSITION }}